### ISSUE TITLE
cant find module models

### ISSUE THREAD

**Issue by DannyLee12** [thinkst/canarytools-python#2]
Issue
---
I've installed canarytools with `pip install canarytools`

When I try and run the following:
```
import canarytools

client = canarytools.Console()

console.devices.all()
```
I get the traceback
```
Traceback (most recent call last):
  File "canary.py", line 1, in <module>
    import canarytools
  File "/Users/daniellee/.virtualenvs/django/lib/python3.5/site-packages/canarytools/__init__.py", line 16, in <module>
    from models.databundles import DataBundle
ImportError: No module named 'models'
```

What is this module and how do I install it?

**Comment by DannyLee12** [comment]
Update
---
This seems to be a python 3 issue. Therefore, my Issue becomes:
1. What version of python does this work for?
2. What must I install to get this to work on python 3.

**Comment by mclmax** [comment]
Hi Danny,

Thanks for picking this up. So the issue was there were a few relative imports of the models sub-package. Relative imports seem to no longer be available in Python 3.

From [](https://www.python.org/dev/peps/pep-0404/): 

> In Python 3, implicit relative imports within packages are no longer available - only absolute imports and explicit relative imports are supported.

You can go ahead and reinstall the module with `pip install canarytools` and you should be good to go!

Thanks Again

**Comment by DannyLee12** [comment]
Thanks, update works.

Closing.
